package org.cocktail.ipweb.serveur;
// Generated by the WOLips TemplateEngine Plug-in at 28 sept. 2006 12:21:15

/*
 * Copyright CRI - Universite de La Rochelle, 1995-2004 
 * 
 * This software is governed by the CeCILL license under French law and
 * abiding by the rules of distribution of free software. You can use, 
 * modify and/or redistribute the software under the terms of the CeCILL
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info". 
 * 
 * As a counterpart to the access to the source code and rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty and the software's author, the holder of the
 * economic rights, and the successive licensors have only limited
 * liability. 
 * 
 * In this respect, the user's attention is drawn to the risks associated
 * with loading, using, modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean that it is complicated to manipulate, and that also
 * therefore means that it is reserved for developers and experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or 
 * data to be ensured and, more generally, to use and operate it in the 
 * same conditions as regards security. 
 * 
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
// Generated by the WOLips TemplateEngine Plug-in

import org.cocktail.fwkcktlwebapp.common.database.CktlUserInfoDB;
import org.cocktail.fwkcktlwebapp.server.CktlWebAction;
import org.cocktail.ipweb.serveur.controlleur.Compte;
import org.cocktail.ipweb.serveur.controlleur.CompteCtrlr;
import org.cocktail.ipweb.serveur.controlleur.PhotoCtrlr;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WORequest;
import com.webobjects.foundation.NSDictionary;

public class DirectAction extends CktlWebAction {
	public static String PAGE_SUIVANTE="PageSuivante";

    public DirectAction(WORequest aRequest) {
        super(aRequest);
    }

    public WOActionResults defaultAction() {
        return pageWithName("Main");
    }

    //Methode pour le CAS
    
    //Tout ok
	@Override
	public WOActionResults loginCasSuccessPage(String netId,
			NSDictionary actionParams) {
		CktlUserInfoDB user = new CktlUserInfoDB(cktlApp.dataBus());
		user.compteForLogin(netId,null,true);
//		LRLog.trace("pwd = "+arg0.password);

		
		if(user.errorCode()!=CktlUserInfoDB.ERROR_NONE)
		{
			return ((Application)cktlApp).pageErreur("Erreur Individu : il y a eut un problème avec l'identification !",context());
		}
		cktlSession().setConnectedUserInfo(user);
		
		// rajout de PO par rapport � la proc�dure standard...
		Session maSession = (Session)cktlSession();

		Test page = (Test) pageWithName("Test");
		page.login = user.login();


		CompteCtrlr monCC;
		monCC = new CompteCtrlr((Session)session(),netId);
		Compte cpte = monCC.compteCourant();
		maSession.setCtrlrCompte(monCC);
		maSession.setPhotoCtrlr(new PhotoCtrlr(maSession));
        	
		/*Main page =  (Main)pageWithName("Main");
		page.login = user.login();
		return page.toProfile();*/
	    return pageWithName("Test");
    }
//	/* (non-Javadoc)
//	 * @see fr.univlr.cri.webapp.CRIWebAction#loginCasSuccessPage(java.lang.String)
//	 */
//	public WOActionResults loginCasSuccessPage(String netid) {
//		// TODO Raccord de m�thode auto-g�n�r�
//		return null;
//	}

	
	/* (non-Javadoc)
	 * @see fr.univlr.cri.webapp.CRIWebAction#loginCasFailurePage(java.lang.String, java.lang.String)
	 */
	public WOActionResults loginCasFailurePage(String errorMessage, String errorCode) {
		// TODO Raccord de m�thode auto-g�n�r�
		return null;
	}

	/* (non-Javadoc)
	 * @see fr.univlr.cri.webapp.CRIWebAction#loginNoCasPage()
	 */
	public WOActionResults loginNoCasPage() {
		// TODO Raccord de m�thode auto-g�n�r�
		return null;
	}

	@Override
	public WOActionResults loginNoCasPage(NSDictionary actionParams) {
		// TODO Auto-generated method stub
		return null;
	}


}