package org.cocktail.ipweb.serveur;
// Generated by the WOLips Templateengine Plug-in at 19 d�c. 2006 17:17:02

import org.cocktail.fwkcktlwebapp.server.components.CktlWebPage;
import org.cocktail.ipweb.serveur.components.page.IPWebDefaultPage;

import com.webobjects.appserver.WOContext;

public class PageLogOut extends IPWebDefaultPage {

    public PageLogOut(WOContext context) {
        super(context);
    }

    public boolean isStateless()
    {
        return true;
    }

    public String applicationURL()
    {
        return cktlApp.getApplicationURL(context());
    }

    public boolean hasSiteURL()
    {
        return cktlApp.mainWebSiteURL() != null;
    }

    public String siteURL()
    {
        return cktlApp.mainWebSiteURL();
    }

}