package org.cocktail.ipweb.serveur.components.pagebo;

import com.webobjects.appserver.WOContext;

// Generated by the WOLips Templateengine Plug-in at 12 févr. 2009 08:20:30
// On va redéfinir ce qu'il faut par rapport à PopUpMultiDiplSemUe, pour gérer une sélection d'EC au lieu d'UE...
public class PopUpMultiDiplSemEc extends PopUpMultiDiplSemUe {
    public PopUpMultiDiplSemEc(WOContext context) {
        super(context);
    }
}