package org.cocktail.ipweb.serveur.components.page.cadres;
// Generated by the WOLips Templateengine Plug-in at 13 juil. 2007 15:31:58

import org.cocktail.ipweb.serveur.Session;
import org.cocktail.ipweb.serveur.controlleur.InscFormationCtrlr;
import org.cocktail.ipweb.serveur.controlleur.UncWebComponent;

import com.webobjects.appserver.*;
import com.webobjects.eocontrol.*;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableArray;
import com.webobjects.foundation.NSNotification;
import com.webobjects.foundation.NSNotificationCenter;
import com.webobjects.foundation.NSSelector;

public class CadreParcours extends UncWebComponent {
    
    public InscFormationCtrlr monFormCt;		// le ctrlr de parcours/semestre pour lequel on affiche le choix de parcours...	
    public EOGenericRecord niemeParcours;	// variable du parcours en cours dans la WORepetition !
    
    private EOGenericRecord parcoursSelected,parcoursInitial;	// Le parcours effectivement s�lectionn�...
//    private boolean cacheParcoursSelected;	// fct� de cache pour n'aller voir qu'une fois au d�but dans les rows
    
    // etapes dans les dialogues :
    private int etapeDialogue, RECCUEIL_CHOIX = 1, CONF_MODIF = 2, ERREUR_CHGT = 3;
    
    // INITS .........................
    public CadreParcours(WOContext context) {
        super(context);
        inits();
        
        // s'enregistrer pour les notifs (chgt de semestre)
        NSNotificationCenter.defaultCenter().addObserver(this,	// on doit me pr�venir moi-m�me !
        	new NSSelector("changeSemestre",		// via cette m�thode
        	new Class [] {NSNotification.class}),		// argument obligatoire !!!
        	"chgtSemestre",					// la signature de la notif qui m�plait
			(Session)this.session());		// instance de celui qui la poste !

        
        System.out.println(" >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Init comp. CadreParcours"); 
    }

    private void inits() {
	//       cacheParcoursSelected = false;
	etapeDialogue = RECCUEIL_CHOIX;
	parcoursSelected = null;

    }
    
//  m�thode invoqu�e par notification a chaque chgt de semestre...
    public void changeSemestre(NSNotification laNotif) {
    	// faire du m�nage pour le dialogue !!!
        inits();
    }
    

    
    //  --------------------------------------------------------    
    //  ---------------- Expr. conditionnelles -----------------
    //  --------------------------------------------------------    
    
    
    // Un dialogue choisi par l'utilisateur est-il en cours ???
    public boolean dialogueChoixInitieParEtud() {
	return ((CadreIp)this.parent()).etatDdeDialogueParcours();
    }
    
    // Etape en cours : reccueil du choix de nouveau parcours ?
    public boolean reccueilChoix() {
        return (etapeDialogue == RECCUEIL_CHOIX);
    }    
    
    // Etape en cours : confirmation du choix de CHANGER de parcours ?
    public boolean confirmationModif() {
        return (etapeDialogue == CONF_MODIF);
    }
    
    // Etape en cours : affichage erreur pour CHANGER de parcours ?
    public boolean erreurModif() {
        return (etapeDialogue == ERREUR_CHGT);
    }
    
    //  --------------------------------------------------------    
    //  ---------------- Valeurs � afficher  -------------------
    //  --------------------------------------------------------    
    

    // Retourner une liste de choix possibles, excluant le parcours actuel si choisi..
    public NSArray getListeChoixParcours() {
	// liste initiale
	NSArray listeInitiale = monFormCt.getParcoursSpecialises();
	EOGenericRecord choixInitial = monFormCt.getParcoursSelected();
	if (choixInitial != null) {
	    NSMutableArray resListe = new NSMutableArray(listeInitiale);
	    resListe.removeObject(monFormCt.getParcoursSelected());
	    return (NSArray)resListe;
	}
	else return listeInitiale;
    }
    
    
// Indiquer le parcours choisi pour le moment par l'�tudiant pour l'inscription en cours ...
    public String parcoursDejaChoisi() {
        String parcoursDC = ((CadreIp)this.parent()).getParcoursInscEnCours();
        if (parcoursDC == null || parcoursDC.length() == 0) {
            return "aucun pour le moment...";
        }
        else return parcoursDC;
    }
    
    // Pour renseigner sur la s�lection initiale du parcours (retourne l'objet initiallement choisi)
    public EOGenericRecord getParcSelected() {
	parcoursInitial = monFormCt.getParcoursSelected(); 
	return 	parcoursInitial; 	// parcours correspondant...
    }
    
    // Pour permettre au component de savoir quelle est la nouvelle s�lection choisie par le user
    public void setParcSelected(EOGenericRecord newParcSelection) {
	// TODO : prendre en compte nouveau parcours !!!!
	parcoursSelected = newParcSelection;
    }

    // Libell� du nouveau parcours... 
    public String getNouveauParcoursChoisi() {
	if (parcoursSelected != null)
	    return (String)parcoursSelected.valueForKey("mparLibelle");
	else return "";
    }
    
    //  --------------------------------------------------------    
    //  ------------------------- ACTIONS ----------------------
    //  --------------------------------------------------------    
    
    // On veut arr�ter le dialogue de choix du parcours !
    public WOComponent annuleChoixParcours() {
        etapeDialogue = RECCUEIL_CHOIX;
	((CadreIp)this.parent()).termineDialogueEnCours();
        return null;
    }
    

    // On veut valider le dialogue de choix du parcours :
    // V�rifier s'il est n�cessaire de faire quelque chose 
    // (ici) A) "vous �tes sur de changer de parcours ?"
    // 	     B) si oui lancer chgt de parcours et terminer le dialogue...
    public WOComponent soumetChoixParcours() {
	if (parcoursSelected != null) {
	    System.out.println("Parcours choisi = " + parcoursSelected.valueForKey("mparLibelle"));
	    
//	  V�rifier s'il est n�cessaire de dder confirmation !?
	    if (parcoursInitial != null && parcoursSelected != parcoursInitial)
		etapeDialogue = CONF_MODIF;
	    else { // sinon effectue l'affectation simple sur parcours et termine le dialogue si pas d'erreur...		
		if (effectueChgtParcours()) 
		    ((CadreIp)this.parent()).termineDialogueEnCours();
		else etapeDialogue = ERREUR_CHGT; 
	    }
	    
	}
	else
	    System.out.println("Parcours choisi = AUCUN !");

//	((CadreIp)this.parent()).termineDialogueEnCours();
        return null;
    }


    public WOComponent confChgtParcours() {
	// TODO : effectuer un chgt de parcours + refresh de l'inscription en cours !!!
	if (effectueChgtParcours()) {
	    etapeDialogue = RECCUEIL_CHOIX;
	    ((CadreIp)this.parent()).termineDialogueEnCours();
	}
	else {
	    // gestion de l'erreur !!!
	    etapeDialogue = ERREUR_CHGT;
	}
	return null;
    }

    //  -------------------------------------------------------------- //
    //  ---- Autres actions internes au composant -------------------- //
    //  -------------------------------------------------------------- //
    
    // Effectuer le lancement du chgt de parcours par le ctrl de semestre, avec les bons params...
    // retourne TRUE si le chgt � bien pu avoir lieu... false sinon
    private boolean effectueChgtParcours() {
	
	Integer ancienParcours, nouveauParcours;
	// extraction des params : 
	// quel est le parcours que l'on quitte ? (si aucun parcours pr�c�dent, renvoyer NULL)
	if (parcoursInitial == null) ancienParcours = new Integer(-1);
	else ancienParcours = (Integer)parcoursInitial.valueForKey("mrsemKey");
	
	// quel est le parcours on l'on va ? (si aucun parcours suivant, renvoyer NULL)
	if (parcoursSelected == null) nouveauParcours = new Integer(-1);
	else nouveauParcours = (Integer)parcoursSelected.valueForKey("mrsemKey");
	
	return monFormCt.changerParcours(ancienParcours,nouveauParcours);
    }
}