// Generated by the WOLips TemplateEngine Plug-in at 2 oct. 2006 12:54:34

import com.webobjects.appserver.*;
import com.webobjects.foundation.NSNotification;
import com.webobjects.foundation.NSNumberFormatter;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSSelector;

import fr.univlr.cri.webapp.*;

public class CadreUE extends UncWebComponent {
	public InscUeCtrlr monUeCtrlr;	// init externe depuis le WORepetition de CadreIp !
	public InscSemestreCtrlr monSemCt;	// le ctrlr de semestre pour lequel on affiche l'UE...	
	
	public InscEcCtrlr ecEnCours;	// variable de parcours du WORepetition...
	
	
	public NSNumberFormatter nbrF;
	
    public CadreUE(WOContext context) {
        super(context);

        nbrF = new NSNumberFormatter();
        nbrF.setDecimalSeparator(",");
        nbrF.setPattern("#;#;#");

//        System.out.println(">>>>>>>>>>>>>>>>>>>>>>>> CREATION CadreUE <<<<<<<<<<<<<<<<<<"+this.toString());
//        
    }

	// message � afficher si mode consult.
	public String stNbreChoixUe() {
		int nbChoix = monUeCtrlr.nbreChoixUe();
		if (nbChoix>0)	return "Nbre d'EC à choix disponibles : "+nbChoix;
		else return "Pas de choix à faire pour cette UE...";
	}
	
	
	public boolean UeAvecChoix() { return (monUeCtrlr.ueAvecChoix()); }
	
	// vrai si l'UE possede au moins un choix modifiable et que l'on est en mode consult...
	public boolean ueChoixEcModeConsult() {
		return (monUeCtrlr.compareCumulEcts()!=0 && !modeModif());
	}

    // renvoyer un pointeur de liste selon le mode modif ou non...
    public NSArray listeEcAffichage() {
    	if (modeModif() && monUeCtrlr.ueAvecChoix()) return monUeCtrlr.getListeEcCt();
    	else return monUeCtrlr.getListeEcIpCt();
    	
    }
    
    public boolean consultEnCours() { return !modeModif(); }
    
    // les appels Javascripts pour afficher ou masquer les diff�rentes Zones (Span et DIV) en fonction
    // de le demande (d�tails ou non) - sauf pour l'UE qui a le focus (forc�ment en mode modif) ...
    
    public String switcherDetails() {
    	return "javascript:switcherZoneDetail('"+idDiv()+"','"+idDivDetail()+
		"','"+idDivMasqueDetail()+"','"+monUeCtrlr.nameChpHiddenUED()+"');";
    }

    
    public String classeDiv() {
    	if (monUeCtrlr.ueDetaillee()) return "hide";
        else return "show";
    }
    
    public String idDiv() {
        return monUeCtrlr.getCodeUe();
    }

    public String classeDivDetail() {
    	if (monUeCtrlr.ueDetaillee()) return "show";
        else return "hide";
    }

    public String idDivDetail() {
        return "D"+monUeCtrlr.getCodeUe();
    }

    public String idDivMasqueDetail() {
        return "H"+monUeCtrlr.getCodeUe();
    }
    
    // pb d'ordre dans les inits... si pas encore initialis�, ce pointeur doit l'�tre lors de sa 1ere r�f�rence, soit ICI !
    public boolean modeModif() {
//    	if (monSemCt == null) monSemCt = ((Session)this.session()).getCtlrSemestreEnCours();
    	return monSemCt.modeModif(); 
    	}
    
    
    // dialogue modal d�ja en cours ?
    public boolean dmec() {
	return ((Session)session()).dmec();
    }
    
    public WOComponent demanderModif() {
	((Session)session()).demarreDM();
		monUeCtrlr.ddeRecalculChoix();
    	if (!monUeCtrlr.ueDetaillee()) monUeCtrlr.afficherDetails();
    	monSemCt.demanderModif(false);
    	setAnchor(monUeCtrlr.getCodeUe());
        return null;
    }
    
    public WOComponent validerModif() {
		monUeCtrlr.ddeRecalculChoix();
    	if (!monSemCt.validerModif(monUeCtrlr)) {  // si toutes les modifs sont bien OK lancer la chaine de validations en cascades...
    		setAnchor(monUeCtrlr.getCodeUe());	// sinon la v�rif s'est mal pass�e : se positionner sur la derni�re erreur survenue ! 
    	}
    	((Session)session()).arreteDM();
    	return null;
    }

    public WOComponent annulerModif() {
    	monSemCt.annulerModif();
    	monUeCtrlr.recalculChoix();

    	((Session)session()).arreteDM();
    	return null;
    }
    
	// construction du message pour OVERLIB pour cet UE (d�tails sur comment corriger un pb d'ECTS )
	public String getMsgOlUe() {
//		"return overlib(' --Pas de Commentaire-- ', CAPTION,'R�union du consortium Cocktail');"
		StringBuffer sb = new StringBuffer("return overlib('Cliquez sur ce lien pour éditer vos choix pour cette UE...'");
		sb.append(",CAPTION,'Info :');");
		return sb.toString();
	}
	
}