// Generated by the WOLips TemplateEngine Plug-in at 26 oct. 2006 15:45:26
//	--> idem CadreUE mais optimisé pour la consult° seule !!!

import com.webobjects.appserver.*;
import com.webobjects.foundation.NSNumberFormatter;
import com.webobjects.foundation.NSArray;

public class CadreUEConsult extends UncWebComponent {

	public InscUeCtrlr monUeCtrlr;	// init externe depuis le WORepetition de CadreIp !
	public InscSemestreCtrlr monSemCt;	// le ctrlr de semestre pour lequel on affiche l'UE...	
	
	public InscEcCtrlr ecEnCours;	// variable de parcours du WORepetition...
	
	
	public NSNumberFormatter nbrF;
	
    public CadreUEConsult(WOContext context) {
        super(context);

        nbrF = new NSNumberFormatter();
        nbrF.setDecimalSeparator(",");
        nbrF.setPattern("#;#;#");
    }

    // renvoyer un pointeur de liste selon le mode modif ou non...
    public NSArray listeEcAffichage() {
    	return monUeCtrlr.getListeEcIpCt();
    }
    
}