package org.cocktail.ipweb.serveur.components;
// Generated by the WOLips Templateengine Plug-in at 9 f�vr. 2007 11:04:47

import org.cocktail.ipweb.serveur.components.page.IPWebDefaultPage;

import com.webobjects.appserver.WOContext;


public class AccesNonAutorise extends IPWebDefaultPage {

    public AccesNonAutorise(WOContext context) {
        super(context);
    }

    public boolean isStateless()
    {
        return true;
    }

    public String applicationURL()
    {
        return cktlApp.getApplicationURL(context());
    }

    public boolean hasSiteURL()
    {
        return cktlApp.mainWebSiteURL() != null;
    }

    public String siteURL()
    {
        return cktlApp.mainWebSiteURL();
    }
}