
import com.webobjects.appserver.*;
import com.webobjects.eocontrol.EOGenericRecord;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSLog;
import com.webobjects.foundation.NSNotification;
import com.webobjects.foundation.NSNotificationCenter;
import com.webobjects.foundation.NSSelector;
import com.webobjects.foundation.NSTimestamp;
import fr.univlr.cri.webapp.*;

// Generated by the WOLips Templateengine Plug-in at 12 févr. 2009 08:20:30
// On va redéfinir ce qu'il faut par rapport à PopUpMultiDiplSemUe, pour gérer une sélection d'EC au lieu d'UE...
public class PopUpMultiDiplSemEc extends PopUpMultiDiplSemUe {
    public PopUpMultiDiplSemEc(WOContext context) {
        super(context);
    }
}