// Generated by the WOLips TemplateEngine Plug-in at 21 oct. 2006 23:29:43

import com.webobjects.appserver.*;


public class IPWebDefaultPage extends CRIDefaultPage {

    public IPWebDefaultPage(WOContext context) {
        super(context);
    }

}