// Generated by the WOLips TemplateEngine Plug-in at 28 sept. 2006 21:43:43

// la page principal pour les IP de l'�tudiant...

import com.webobjects.appserver.*;

import fr.univlr.cri.webapp.*;

public class PageIP extends CRIWebComponent {

    public PageIP(WOContext context) {
        super(context);
    }

    public WOActionResults toPageScolariteAnterieureEtu() {
		PageScolariteAnterieureEtud nextPage = (PageScolariteAnterieureEtud)pageWithName(PageScolariteAnterieureEtud.class.getName());
		IndividuCtrlr individuCt = ((Session)criSession()).getICEtudiant(); 
        InscriptionCtrlr inscCt = individuCt.monCInsc();
        nextPage.setLesInscriptionsParAnnee(inscCt.getTousLesDiplAnneeCtrlParAnneeUniv());
        nextPage.setPreviousPage(getPage());
		return nextPage;
	}
    
	private WOComponent getPage() {
		WOComponent currentComponent = this;
		while (!currentComponent._isPage()) {
			currentComponent = currentComponent.parent();
		}
		return currentComponent;
	}
    
}