// Generated by the WOLips TemplateEngine Plug-in at 28 sept. 2006 21:43:43

// la page principal pour les IP de l'étudiant...

import com.webobjects.appserver.*;
import fr.univlr.cri.webapp.*;

public class PageIP extends CRIWebComponent {

    public PageIP(WOContext context) {
        super(context);
    }

}