// Generated by the WOLips Templateengine Plug-in at 9 févr. 2007 11:04:47

import com.webobjects.appserver.*;
import fr.univlr.cri.webapp.CRIWebApplication;
import fr.univlr.cri.webapp.CRIWebPage;


public class AccesNonAutorise extends CRIWebPage {

    public AccesNonAutorise(WOContext context) {
        super(context);
    }

    public boolean isStateless()
    {
        return true;
    }

    public String applicationURL()
    {
        return criApp.getApplicationURL(context());
    }

    public boolean hasSiteURL()
    {
        return criApp.mainWebSiteURL() != null;
    }

    public String siteURL()
    {
        return criApp.mainWebSiteURL();
    }
}