// Generated by the WOLips Templateengine Plug-in at 19 déc. 2006 17:17:02

import com.webobjects.appserver.*;
import fr.univlr.cri.webapp.CRIWebApplication;
import fr.univlr.cri.webapp.CRIWebPage;

public class PageLogOut extends CRIWebPage {

    public PageLogOut(WOContext context) {
        super(context);
    }

    public boolean isStateless()
    {
        return true;
    }

    public String applicationURL()
    {
        return criApp.getApplicationURL(context());
    }

    public boolean hasSiteURL()
    {
        return criApp.mainWebSiteURL() != null;
    }

    public String siteURL()
    {
        return criApp.mainWebSiteURL();
    }

}