package org.cocktail.ipweb.serveur.components.page;
// Generated by the WOLips TemplateEngine Plug-in at 21 oct. 2006 23:29:43

import org.cocktail.fwkcktlwebapp.server.components.CktlWebPage;

import com.webobjects.appserver.WOContext;


public class IPWebDefaultPage extends CktlWebPage{

    public IPWebDefaultPage(WOContext context) {
        super(context);
    }

}