package org.cocktail.ipweb.serveur.components.page;
// Generated by the WOLips TemplateEngine Plug-in at 28 sept. 2006 21:43:43

// la page principal pour les IP de l'�tudiant...


import org.cocktail.ipweb.serveur.Session;
import org.cocktail.ipweb.serveur.controlleur.IndividuCtrlr;
import org.cocktail.ipweb.serveur.controlleur.InscriptionCtrlr;

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class PageIP extends IPWebDefaultPage {

    public PageIP(WOContext context) {
        super(context);
    }

    public WOActionResults toPageScolariteAnterieureEtu() {
		PageScolariteAnterieureEtud nextPage = (PageScolariteAnterieureEtud)pageWithName(PageScolariteAnterieureEtud.class.getName());
		IndividuCtrlr individuCt = ((Session)cktlSession()).getICEtudiant(); 
        InscriptionCtrlr inscCt = individuCt.monCInsc();
        nextPage.setLesInscriptionsParAnnee(inscCt.getTousLesDiplAnneeCtrlParAnneeUniv());
        nextPage.setPreviousPage(getPage());
		return nextPage;
	}
    
	private WOComponent getPage() {
		WOComponent currentComponent = this;
		while (!currentComponent._isPage()) {
			currentComponent = currentComponent.parent();
		}
		return currentComponent;
	}
    
}